train_HATS_node:
			python src/main.py \
			--feature_list return \
			--feat_att \
			--rel_att \
			--test_phase $(test_phase) \
			--train_proportion $(train_proportion) \
			--save_dir $(save_dir) \
